

1.   ***bigdata.csv***-contains all the data



In [ ]:
!wget https://www.dropbox.com/s/6klueabszon0tkw/bigdata.csv?dl=0


--2022-01-31 08:14:24--  https://www.dropbox.com/s/6klueabszon0tkw/bigdata.csv?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.81.18, 2620:100:6034:18::a27d:5412
Connecting to www.dropbox.com (www.dropbox.com)|162.125.81.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/6klueabszon0tkw/bigdata.csv [following]
--2022-01-31 08:14:25--  https://www.dropbox.com/s/raw/6klueabszon0tkw/bigdata.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc1640981f6a4c0d73a2a98d47a7.dl.dropboxusercontent.com/cd/0/inline/Be2ZvSGDx1Vz5Zmq15A27TIn21JJg7-HBApAtJHVJbxGEx7p0Bj7ZmYKnWSZWRihFqOfN3goe6826FfUBlV54_c3onCK2v_8ux9eji5DSFdaIOnoHa0t-dnpnKU594o9Pu2qitFuIl8kSjI0RwUlmKiy/file# [following]
--2022-01-31 08:14:25--  https://uc1640981f6a4c0d73a2a98d47a7.dl.dropboxusercontent.com/cd/0/inline/Be2ZvSGDx1Vz5Zmq15A27TIn21JJg7-HBApAtJHVJbxGEx7p0Bj7ZmYKnWSZWRihFqOfN3goe6826FfUBlV54

In [ ]:
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout
from gensim.models.keyedvectors import KeyedVectors  
import numpy as np




In [ ]:
import shutil

shutil.rmtree('/content/gossipcop')

FileNotFoundError: ignored

Dataset-TASK2

In [ ]:
!wget https://www.dropbox.com/s/hrquhbq5dj7j8j6/fakenewsnet_dataset.zip?dl=0

--2022-01-17 20:43:00--  https://www.dropbox.com/s/hrquhbq5dj7j8j6/fakenewsnet_dataset.zip?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.6.18, 2620:100:6019:18::a27d:412
Connecting to www.dropbox.com (www.dropbox.com)|162.125.6.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/hrquhbq5dj7j8j6/fakenewsnet_dataset.zip [following]
--2022-01-17 20:43:00--  https://www.dropbox.com/s/raw/hrquhbq5dj7j8j6/fakenewsnet_dataset.zip
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucaff012b1e06759c129d8db11f7.dl.dropboxusercontent.com/cd/0/inline/Bd9T9boMttG8I01Jt_fLYigQ0gOb8iEUIq4RUNhW5AqX9anU165nFgJSVq6zkiO3lRM29ClcHWYJJEoixZPY2lbJ6Y44Jzgxa26ewaLj3HD7LT1x5oTZCfgakZXJz8jSa2S5RIt-H_WIvRhF7wYF4KII/file# [following]
--2022-01-17 20:43:01--  https://ucaff012b1e06759c129d8db11f7.dl.dropboxusercontent.com/cd/0/inline/Bd9T9boMttG8I01Jt_fLYigQ0gOb8iEUIq4RUNhW5AqX9anU165n

In [ ]:
!unzip '/content/fakenewsnet_dataset.zip?dl=0'

In [ ]:
from os import listdir
from os.path import isfile, join,isdir
import pandas as pd
import json
import glob
import statistics
mypath="/content/politifact/fake"
onlyfiles = [f for f in listdir(mypath) if isdir(join(mypath, f))]

list_c=["title","text","meta_data","authors","publish_date","source","summary"]
df=pd.DataFrame(columns=list_c)
dictor={}

for i in onlyfiles:
   dictor.clear()
   line=join(join(mypath,i),"news content.json") 
   if(isfile(line)):
     with open(line) as json_data:
       data=json.load(json_data)
       dictor["type"]=0
       for c in list_c:
         dictor[c]=data[c]
       df=df.append(dictor,ignore_index=True)
        

mypath="/content/politifact/real"
onlyfiles = [f for f in listdir(mypath) if isdir(join(mypath, f))]


for i in onlyfiles:
   dictor.clear()
   line=join(join(mypath,i),"news content.json") 
   if(isfile(line)):
     with open(line) as json_data:
       data=json.load(json_data)
       dictor["type"]=1
       for c in list_c:
         dictor[c]=data[c]
       df=df.append(dictor,ignore_index=True)

mypath="/content/gossipcop/real"
onlyfiles = [f for f in listdir(mypath) if isdir(join(mypath, f))]


for i in onlyfiles:
   dictor.clear()
   line=join(join(mypath,i),"news content.json") 
   if(isfile(line)):
     with open(line) as json_data:
       data=json.load(json_data)
       dictor["type"]=1
       for c in list_c:
         dictor[c]=data[c]
       df=df.append(dictor,ignore_index=True)

mypath="/content/gossipcop/fake"
onlyfiles = [f for f in listdir(mypath) if isdir(join(mypath, f))]


for i in onlyfiles:
   dictor.clear()
   line=join(join(mypath,i),"news content.json") 
   if(isfile(line)):
     with open(line) as json_data:
       data=json.load(json_data)
       dictor["type"]=0
       for c in list_c:
         dictor[c]=data[c]
       df=df.append(dictor,ignore_index=True)





In [ ]:
df.to_csv('data_twitter.csv')

In [ ]:
#Download data_twitter.csv
!wget https://www.dropbox.com/s/l3gf2jmh4n60nhb/data_twitter.csv?dl=0

#Dataframe Pandas
df=pd.read_csv('/content/data_twitter.csv?dl=0')

--2022-01-17 20:59:20--  https://www.dropbox.com/s/l3gf2jmh4n60nhb/data_twitter.csv?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.6.18, 2620:100:6019:18::a27d:412
Connecting to www.dropbox.com (www.dropbox.com)|162.125.6.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/l3gf2jmh4n60nhb/data_twitter.csv [following]
--2022-01-17 20:59:20--  https://www.dropbox.com/s/raw/l3gf2jmh4n60nhb/data_twitter.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc9ff12b03552eb4cb438f819c2a.dl.dropboxusercontent.com/cd/0/inline/Bd_BSf3ZQaeEgybwzxDjscBoVzYk2L7Ne-uQsPzG21x9Ai0QIxgINHtBm_ZYbZYYth6FU5dqzyeKc2EctqGOoCh8S2rRfbKJ8bmpHpp8NUJHfF0bsbRZWGNd7P2L_6MBSy3e1diz1eORxmrXYU6oeSWu/file# [following]
--2022-01-17 20:59:20--  https://uc9ff12b03552eb4cb438f819c2a.dl.dropboxusercontent.com/cd/0/inline/Bd_BSf3ZQaeEgybwzxDjscBoVzYk2L7Ne-uQsPzG21x9Ai0QIxgINHtBm_ZYbZYYth6FU5dqz

In [ ]:
display(df.iloc[15555])

Unnamed: 0                                                  15555
title           Today in Entertainment: Olivia de Havilland sc...
text            Hugh Hefner spoke with the L.A. Times often — ...
meta_data       {'og': {'title': "Today in Entertainment: Oliv...
authors                                                        []
publish_date                                                  NaN
source                                    https://www.latimes.com
summary                                                       NaN
type                                                            1
Name: 15555, dtype: object

Dataset#1

In [ ]:
df=pd.read_csv('/content/bigdata.csv?dl=0')

In [ ]:
df

Unnamed: 0  ... type
0               0  ...    1
1               1  ...    0
2               2  ...    1
3               3  ...    1
4               4  ...    1
...           ...  ...  ...
31744       31744  ...    1
31745       31745  ...    1
31746       31746  ...    1
31747       31747  ...    1
31748       31748  ...    1

[31749 rows x 5 columns]

Data preprocessing

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X=df["text"]
y=df["type"]

In [ ]:
y

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
20864    0.0
20865    0.0
20866    0.0
20867    0.0
20868    0.0
Name: type, Length: 20869, dtype: float64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True)

In [ ]:
print(X_train)

13528    After 154 shows, Justin Bieber is bowing out o...
11382    Shannon Beador is starting off this season of ...
11586    Justin Bieber and his mom, Pattie Mallette, we...
15372    For the first time since human gummy bear Mile...
20182    Portia de Rossi made an appearance on The Elle...
                               ...                        
15923    It pays to be on one of the biggest sitcoms of...
2487     Canadian professional basketball player\n\nTri...
12144    The Grammy winner reveals details about her co...
17588    Catherine Oxenberg is writing about her contin...
9140     Tessa Thompson opens up about her sexuality: '...
Name: text, Length: 14608, dtype: object


In [ ]:
import gensim
from gensim.parsing.porter import PorterStemmer
import re

In [ ]:
p = PorterStemmer()
corpus=[]
X_train1 = X_train.astype(str).str.split()
for word in X_train1:
  


  

In [ ]:
type(X_train)

pandas.core.series.Series

In [ ]:
# for word in df_train1["content"]:
#   review=p.stem_sentence(word)
#   review = ''.join(review)
#   corpus.append(review)
corpus=[]
sentence_compus=""
for sentence in tokenz:
  #print(sentence)
  for word in sentence:
    sentence_compus=sentence_compus+" "+word 
  
  review=p.stem_sentence(sentence_compus)  
  review = ''.join(review)  
  
  corpus.append(review)
  
  sentence_compus=""

In [ ]:
corpus

Output hidden; open in https://colab.research.google.com to view.

BigData-Dataset

In [ ]:
dp=pd.read_csv('/content/bigdata.csv?dl=0')

For Fake News **Type**=1
For Realiable New **Type**=0




In [ ]:
dp.head()

Unnamed: 0  ... type
0           0  ...    1
1           1  ...    0
2           2  ...    1
3           3  ...    1
4           4  ...    1

[5 rows x 5 columns]

In [ ]:
dp.shape

(31749, 5)

Spliting the bigdata.csv in two data sets

In [ ]:
df_train1 = dp.iloc[:22000]
df_test2 = dp.iloc[22001:31749]

In [ ]:
del df_train1["Unnamed: 0"]

In [ ]:
df_train1.head()
del df_train1["id"]

In [ ]:
df_test2.head()

Unnamed: 0  ... type
22001       22001  ...    1
22002       22002  ...    1
22003       22003  ...    1
22004       22004  ...    1
22005       22005  ...    1

[5 rows x 5 columns]

In [ ]:
df_train1.to_csv('/content/data_train.csv')
df_test2.to_csv('/content/data_test.csv')

In [ ]:
df_train1

id  ... type
0          0  ...    1
1          1  ...    0
2          2  ...    1
3          3  ...    1
4          4  ...    1
...      ...  ...  ...
21995  21995  ...    1
21996  21996  ...    1
21997  21997  ...    1
21998  21998  ...    1
21999  21999  ...    1

[22000 rows x 4 columns]

In [ ]:
df_train1.insert(0, 'id', range(0,len(df_train1)))

In [ ]:
del df["Unnamed: 0"]
del df["id"]
df.insert(0, 'id', range(0,len(df)))

In [ ]:
df

id  ... type
0          0  ...    1
1          1  ...    0
2          2  ...    1
3          3  ...    1
4          4  ...    1
...      ...  ...  ...
31744  31744  ...    1
31745  31745  ...    1
31746  31746  ...    1
31747  31747  ...    1
31748  31748  ...    1

[31749 rows x 4 columns]

In [ ]:
import gensim
from gensim.parsing.porter import PorterStemmer
import re
#df_train1.content[0]
#df_train1=df_train1.dropna()
#df_test2=df_test2.dropna()
df=df.dropna()

p.stem_sentence


In [ ]:
p = PorterStemmer()
corpus = []
for word in df["content"]:
  review=p.stem_sentence(word)
  review = ''.join(review)
  corpus.append(review)

In [ ]:
review

'mgx miner strengthen leadership with former execut at berkshir hathawai energi renew % of reader think thi stori is fact. add your two cents. headline: bitcoin & blockchain search exce trump! blockchain stock ar next! share in mgx miner inc (cse:xmg, otcqb:mgxmf) advanc on tuesdai as it bolster it manag by hire randi w keller as vice presid of busi development. keller is formerli the director of busi development, transmiss and land assets, for berkshir hathawai energi renewables, a hold compani control by warren buffett’ berkshir hathawai inc. “we welcom randi keller to the mgx team and look forward to util hi deep industri experi as we target addit acquisit and strateg partnership throughout california,” said mgx presid jare lazerson. “we continu to build our u.s. leadership team and more specif our california-focus team as we believ the state offer a multitud of opportun to implement lithium extract and water purif systems.” keller wa respons for the develop of large-scal renew ener

In [ ]:
corpus

Output hidden; open in https://colab.research.google.com to view.

In [23]:
voc=1000

In [ ]:
onehot_repr=[one_hot(words,voc)for words in corpus] 
onehot_repr

In [28]:
sent_length=1300
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0 ... 895 784 704]
 [  0   0   0 ... 879 735 478]
 [  0   0   0 ... 875 888 786]
 ...
 [187 243 837 ... 909 626 888]
 [  0   0   0 ...  67 431 722]
 [  0   0   0 ... 279  41 204]]


In [ ]:
embedded_docs.shape

(14608, 800)

In [ ]:
#gensim.utils.simple_preprocess(df_train1.content[0])
#df_train1=df_train1.dropna()
#df_test2=df_test2.dropna()
tw_train=pd.DataFrame({'content':X_train.values})
tw_train=tw_train.dropna()
content_text=tw_train.content.apply(gensim.utils.simple_preprocess)


In [30]:
content_text

NameError: ignored

In [31]:
embedded_docs

array([[  0,   0,   0, ..., 895, 784, 704],
       [  0,   0,   0, ..., 879, 735, 478],
       [  0,   0,   0, ..., 875, 888, 786],
       ...,
       [187, 243, 837, ..., 909, 626, 888],
       [  0,   0,   0, ...,  67, 431, 722],
       [  0,   0,   0, ..., 279,  41, 204]], dtype=int32)

In [32]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dropout(0.1))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 1300, 40)          40000     
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dropout (Dropout)           (None, 100)               0         
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 96,501
Trainable params: 96,501
Non-trainable params: 0
_________________________________________________________________
None


In [39]:
y=df['type']

In [40]:
X=df.drop('type',axis=1)

In [41]:
len(embedded_docs),y.shape

(31152, (31152,))

In [42]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [43]:
X.shape,y.shape

((31152, 3), (31152,))

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.3,shuffle=True)

In [45]:
model.fit(X_train,y_train,validation_data=(np.asarray(X_test).astype('float32'),y_test),epochs=10,batch_size=128)

Epoch 1/10
171/171 [==============================] - 596s 3s/step - loss: 0.3910 - accuracy: 0.8207 - val_loss: 0.3100 - val_accuracy: 0.8659
Epoch 2/10
171/171 [==============================] - 590s 3s/step - loss: 0.2628 - accuracy: 0.8959 - val_loss: 0.2787 - val_accuracy: 0.8785
Epoch 3/10
171/171 [==============================] - 586s 3s/step - loss: 0.2340 - accuracy: 0.9075 - val_loss: 0.2381 - val_accuracy: 0.9115
Epoch 4/10
171/171 [==============================] - 589s 3s/step - loss: 0.3047 - accuracy: 0.8750 - val_loss: 0.2471 - val_accuracy: 0.9057
Epoch 5/10
171/171 [==============================] - 590s 3s/step - loss: 0.2433 - accuracy: 0.9017 - val_loss: 0.2616 - val_accuracy: 0.8990
Epoch 6/10
171/171 [==============================] - 586s 3s/step - loss: 0.2526 - accuracy: 0.8981 - val_loss: 0.2354 - val_accuracy: 0.9122
Epoch 7/10
171/171 [==============================] - 585s 3s/step - loss: 0.3456 - accuracy: 0.8537 - val_loss: 0.3116 - val_accuracy: 0.8743

KeyboardInterrupt: ignored

In [46]:
y_pred1=(model.predict(X_test) > 0.5).astype("int32")


In [47]:
from sklearn.metrics import confusion_matrix

In [48]:
confusion_matrix(y_test,y_pred1)

array([[2814,  453],
       [ 339, 5740]])

In [49]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1)

0.9152578643269849

In [50]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.89      0.86      0.88      3267
           1       0.93      0.94      0.94      6079

    accuracy                           0.92      9346
   macro avg       0.91      0.90      0.91      9346
weighted avg       0.91      0.92      0.91      9346

